plex:
  image: linuxserver/plex:1.41.3
  downloads_folder:
    size: 5Gi
  config_folder:
    size: 1Gi
  host: plex.k3s.bokors.net
  resources:
    requests:
      cpu: 50m
      memory: 150Mi
    limits:
      cpu: 250m
      memory: 250Mi
  middlewares: []
  claim: claim-D64oYQP2NMmXF8vjrDiY  