apiVersion: v1
kind: Namespace
metadata:
  name: librespeed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: librespeed-deploy
  namespace: librespeed
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: librespeed
  template:
    metadata:
      labels:
        app: librespeed
    spec:
      containers:
      - name: librespeed
        image: linuxserver/librespeed
        ports:
        - name: web
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: librespeed-svc
  namespace: librespeed
  labels:
    app: librespeed
spec:
  type: ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort: 80
    protocol: TCP
  selector:
    app: librespeed
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: librespeed-ingress
  namespace: librespeed
spec:
  rules:
  - host: "librespeed.bokors.net"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: librespeed-svc 
            port:
              number: 80
          
