apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-qbittorrent-svc
  namespace: qbittorrent
  labels:
    app: qbittorrent
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app: qbittorrent
---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: qbittorrent-ingress
#spec:
#  rules:
#  - host: "qbittorrent.k3s.bokors.net"
#    http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: {{ .Release.Name }}-qbittorrent-svc 
#            port:
#              number: 8080
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-qbittorrent-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ required "A valid qbittorent host is required!" .Values.qbittorrent.host }}`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-qbittorrent-svc
          port: 8080
      {{- if .Values.qbittorrent.middlewares }}
      middlewares:
      {{- range $v := .Values.qbittorrent.middlewares }}
        - name: {{ $v }}
      {{- end }}
      {{- end }}
  tls:
  - hosts:
    - qbittorrent.k3s.bokors.net
    secretName: qbittorrent-tls-secret              
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qbittorrent-cert
  namespace: qbittorrent
spec:
  secretName: qbittorrent-tls-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - qbittorrent.k3s.bokors.net