apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-qbittorrent-svc
  namespace: qbittorrent
  labels:
    app: qbittorrent
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app: qbittorrent
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent-ingress-https
  namespace: qbittorrent
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/redirect-entry-point: websecure
spec:
  rules:
  - host: "{{ .Values.qbittorrent.host }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-qbittorrent-svc
            port:
              number: 8080
  tls:
  - hosts:
    - "{{ .Values.qbittorrent.host }}"
    secretName: qbittorrent-tls-secret           
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qbittorrent-cert
  namespace: qbittorrent
spec:
  secretName: qbittorrent-tls-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - {{.Values.qbittorrent.host}}