apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-fs01-bdpthu-qbit-media
spec:
  capacity:
    storage: 3500Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  nfs:
    path: /volume1/MEDIA
    server: 192.168.10.10
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-downloads-plex-media
  namespace: qbittorrent
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: {{ .Values.qbittorrent.downloads_folder.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: qbittorrent
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.qbittorrent.config_folder.size }}