apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-qbittorrent-downloads
  namespace: qbittorrent
spec:
  accessModes:
  - ReadWriteMany
  stiorageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.qbittorrent.downloads_folder.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-qbittorrent-config
  namespace: qbittorrent
spec:
  accessModes:
  - ReadWriteOnce
  stiorageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.qbittorrent.config_folder.size }}