apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-downloads-plex-media
  namespace: qbittorrent
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: {{ .Values.qbittorrent.downloads_folder.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: qbittorrent
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.qbittorrent.config_folder.size }}