apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-downloads-plex-media-pv
  namespace: k3s-global
spec:
  capacity:
    storage: {{ .Values.qbittorrent.downloads_folder.size }}
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  persistentVolumeReclaimPolicy: Delete
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '3'
      staleReplicaTimeout: '2880'
    volumeHandle: existing-longhorn-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-media
  namespace: qbittorrent
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.qbittorrent.downloads_folder.size }}
  volumeName: qbittorrent-downloads-plex-media-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: qbittorrent
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.qbittorrent.config_folder.size }}