---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-downloads-plex-media
  namespace: qbittorrent
spec:
  capacity:
    storage: {{ .Values.qbittorrent.downloads_folder.size }}
  accessModes:
  - ReadWriteMany
  nfs:
    path: /volume1/MEDIA
    server: 192.168.10.10
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: qbittorrent
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.qbittorrent.config_folder.size }}