apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-plex-config
  namespace: plex-media-server
spec:
  accessModes:
  storageClassName: longhorn
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.plex.config_folder.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-plex-media
  namespace: plex-media-server
spec:
  accessModes:
  storageClassName: longhorn
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.plex.downloads_folder.size }}
  volumeName: qbittorrent-downloads-pv