apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-downloads-plex-media-pv
spec:
  capacity:
    storage: {{ .Values.qbittorrent.downloads_folder.size }}
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-storage
  nfs:
    path: /volume1/MEDIA
    server: 192.168.10.10
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-plex-config
  namespace: plex-media-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.plex.config_folder.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-downloads-plex-media
  namespace: plex-media-server
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
  resources:
    requests:
      storage: {{ .Values.plex.downloads_folder.size }}