qbittorrent:
  image: linuxserver/qbittorrent:5.0.3
  downloads_folder:
    size: 5Gi
  config_folder:
    size: 3Gi
  host: toto
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 250m
      memory: 150Mi
  middlewares: []

  secrets: {}